export const CART_COOKIE = 'CART'

export const COLORS_POOL = {
    1: { id: 1, id_string: 'burnt-orange', colors: ['#e0824b'], title: 'Burnt Orange' },
    2: { id: 2, id_string: 'brown', colors: ['#31221d'], title: 'Brown' },
    358: { id: 358, id_string: 'sport-grey', colors: ['#cacaca'], title: 'Sport Grey' },
    362: { id: 362, id_string: 'dark-chocolate', colors: ['#31221d'], title: 'Dark Chocolate' },
    364: { id: 364, id_string: 'military-green', colors: ['#585c3b'], title: 'Military Green' },
    367: { id: 367, id_string: 'dark-heather', colors: ['#454545'], title: 'Dark Heather' },
    369: { id: 369, id_string: 'irish-green', colors: ['#129447'], title: 'Irish Green' },
    392: { id: 392, id_string: 'light-blue', colors: ['#d6e6f7'], title: 'Light Blue' },
    395: { id: 395, id_string: 'maroon', colors: ['#642838'], title: 'Maroon' },
    418: { id: 418, id_string: 'black', colors: ['#000000'], title: 'Black' },
    423: { id: 423, id_string: 'red', colors: ['#c62A32'], title: 'Red' },
    424: { id: 424, id_string: 'charcoal', colors: ['#585559'], title: 'Charcoal' },
    425: { id: 425, id_string: 'royal', colors: ['#084f97'], title: 'Royal' },
    511: { id: 511, id_string: 'navy', colors: ['#1a2237'], title: 'Navy' },
    521: { id: 521, id_string: 'white', colors: ['#ffffff'], title: 'White' },
    1058: { id: 1058, id_string: 'royal-white', colors: ['#2b4da4', '#ffffff'], title: 'Royal/White' },
    1062: { id: 1062, id_string: 'black-white', colors: ['#000000', '#ffffff'], title: 'Black/White' },
    1535: { id: 1535, id_string: 'asphalt-white', colors: ['#525455', '#ffffff'], title: 'Asphalt/White' },
    1536: { id: 1536, id_string: 'scarlet-white', colors: ['#bA2326', '#ffffff'], title: 'Scarlet/White' },
    1750: { id: 1750, id_string: 'white-black', colors: ['#ffffff', '#000000'], title: 'White/Black' },
    1792: { id: 1792, id_string: 'green-white', colors: ['#026539', '#ffffff'], title: 'Green/White' },
    1795: { id: 1795, id_string: 'navy-white', colors: ['#1a1f35', '#ffffff'], title: 'Navy/White' },
}

export const SEARCH_COLORS = [
    { id: 1, color_display: { color: '#000000', title: 'Black', id_string: 'black' }, colors: [COLORS_POOL[418], COLORS_POOL[1062]] },
    { id: 3, color_display: { color: '#525455', title: 'Grey', id_string: 'grey' }, colors: [COLORS_POOL[367], COLORS_POOL[424], COLORS_POOL[1535]] },
    { id: 3, color_display: { color: '#cacaca', title: 'Light Grey', id_string: 'light-grey' }, colors: [COLORS_POOL[358]] },
    { id: 2, color_display: { color: '#ffffff', title: 'White', id_string: 'white' }, colors: [COLORS_POOL[521]] },
    { id: 4, color_display: { color: '#2b4da4', title: 'Blue', id_string: 'blue' }, colors: [COLORS_POOL[425], COLORS_POOL[1058]] },
    { id: 5, color_display: { color: '#1a1f35', title: 'Navy', id_string: 'navy' }, colors: [COLORS_POOL[511], COLORS_POOL[1795]] },
    { id: 6, color_display: { color: '#026539', title: 'Green', id_string: 'green' }, colors: [COLORS_POOL[364], COLORS_POOL[369], COLORS_POOL[1792]] },
    { id: 7, color_display: { color: '#e0824b', title: 'Orange', id_string: 'orange' }, colors: [COLORS_POOL[1]] },
    { id: 8, color_display: { color: '#c62A32', title: 'Red', id_string: 'red' }, colors: [COLORS_POOL[423], COLORS_POOL[1536]] },
    { id: 9, color_display: { color: '#31221d', title: 'Brown', id_string: 'brown' }, colors: [COLORS_POOL[2]] },
]

export const SIZES_POOL = [
    { id: 14, title: 'S' },
    { id: 15, title: 'M' },
    { id: 16, title: 'L' },
    { id: 17, title: 'XL' },
    { id: 18, title: '2XL' },
]

export const PROVIDERS_POOL = [
    { id: 29, title: 'Monster Digital' },
    { id: 87, title: 'Print Logistic' },
    { id: 72, title: 'Print Clever' },
    { id: 26, title: 'Textildruck Europa' },
    { id: 27, title: 'Print Geek' },
    { id: 6, title: 'T Shirt and Sons' },
]

export const COLLECTIONS = [
    { id: 'sound-vibes', title: 'Sound Vibes', color: '#252c5e' },
    { id: 'gamer-life', title: 'Gamer Life', color: null },
]

export const MENU_OPTIONS = [
    { title: 'Home', type: 'link', href: '/' },
    { title: 'Departments', type: 'forward', value: 'departments' },
    { title: 'Collections', type: 'forward', value: 'collections' },
    { title: 'Support', type: 'link', href: '/support' },
    { title: 'About us', type: 'link', href: '/about-us' },
]

export const MENU_FORWARD_OPTIONS = {
    departments: [
        { title: 'T-Shirts', type: 'link', href: '/search?v=t-shirt' },
        { title: 'Hoodies', type: 'link', href: '/search?v=hoodie' },
    ],
    products: [
        { title: 'T-Shirts', type: 'link', href: '/search?v=t-shirt' },
        { title: 'Hoodies', type: 'link', href: '/search?v=hoodie' },
        { title: 'Long Sleeves', type: 'link', href: '/search?v=long+sleeves' },
        { title: 'Socks', type: 'link', href: '/search?v=socks' },
        { title: 'Mugs', type: 'link', href: '/search?v=mugs' },
        { title: 'Phone Cases', type: 'link', href: '/search?v=phone+cases' },
        { title: 'Pillows', type: 'link', href: '/search?v=pillows' },
        { title: 'Bottles & Tumblers', type: 'link', href: '/search?v=bottles+tumblers' },
        { title: 'Hats', type: 'link', href: '/search?v=hats' },
        { title: 'Blankets', type: 'link', href: '/search?v=blankets' },
        { title: 'Poster', type: 'link', href: '/search?v=poster' },
        { title: 'Apron', type: 'link', href: '/search?v=apron' },
        { title: 'Towels', type: 'link', href: '/search?v=towels' },
        { title: 'Shoes', type: 'link', href: '/search?v=shoes' },
        { title: 'Tank Tops', type: 'link', href: '/search?v=tank+tops' },
        { title: 'Bottoms', type: 'link', href: '/search?v=bottoms' },
    ],
    collections: [
        { title: 'Music', type: 'link', href: '/search?h=music' },
        { title: 'Zombies', type: 'link', href: '/search?v=zombies' },
        { title: 'Games', type: 'link', href: '/search?h=games' }
    ]
}

export const TAGS_POOL = [
    'bed',
    'computer',
    'couples',
    'funny',
    'games',
    'glitch',
    'guitar',
    'halloween',
    'home',
    'hoodie',
    'music',
    'pillow',
    'raglan-tee',
    'rock',
    'zombies',
]

export const itemsNavBar = [
    { value: 't-shirt', title: 'T-SHIRTS' },
    { value: 'hoodie', title: 'HOODIES' },
    { value: 'mugs', title: 'MUGS' },
    { value: 'bags', title: 'BAGS' },
    { value: 'accessories', title: 'ACCESSORIES' },
    { value: 'pillows', title: 'PILLOWS' },
    { value: 'socks', title: 'SOCKS' },
]

export const PRODUCT_TYPES = [
    {
        id: 't-shirt',
        title: 'T-Shirt',
        color: '#1189C4',
        providers: [29, 87, 72],
        colors: [521, 418, 358, 362, 364, 369, 392, 424, 425, 511, 423],
        sizes: [14, 15, 16, 17, 18],
        variants: [
            {
                id: 38164,
                cost: 959,
                price: 1598,
                title: "Black / S",
                grams: 111,
                color_id: 418,
                size_id: 14,
            },
            {
                id: 38166,
                cost: 959,
                price: 1598,
                title: "Military Green / S",
                grams: 111,
                color_id: 364,
                size_id: 14,
            },
            {
                id: 38153,
                cost: 959,
                price: 1598,
                title: "Charcoal / S",
                grams: 111,
                color_id: 424,
                size_id: 14,
            },
            {
                id: 38155,
                cost: 959,
                price: 1598,
                title: "Dark Chocolate / S",
                grams: 111,
                color_id: 362,
                size_id: 14,
            },
            {
                id: 38156,
                cost: 959,
                price: 1598,
                title: "Irish Green / S",
                grams: 111,
                color_id: 369,
                size_id: 14,
            },
            {
                id: 38157,
                cost: 959,
                price: 1598,
                title: "Light Blue / S",
                grams: 111,
                color_id: 392,
                size_id: 14,
            },
            {
                id: 38158,
                cost: 959,
                price: 1598,
                title: "Navy / S",
                grams: 111,
                color_id: 511,
                size_id: 14,
            },
            {
                id: 38160,
                cost: 959,
                price: 1598,
                title: "Red / S",
                grams: 111,
                color_id: 423,
                size_id: 14,
            },
            {
                id: 38161,
                cost: 959,
                price: 1598,
                title: "Royal / S",
                grams: 111,
                color_id: 425,
                size_id: 14,
            },
            {
                id: 38163,
                cost: 959,
                price: 1598,
                title: "White / S",
                grams: 111,
                color_id: 521,
                size_id: 14,
            },
            {
                id: 38162,
                cost: 959,
                price: 1598,
                title: "Sport Grey / S",
                grams: 111,
                color_id: 358,
                size_id: 14,
            },
            {
                id: 38178,
                cost: 959,
                price: 1598,
                title: "Black / M",
                grams: 120,
                color_id: 418,
                size_id: 15,
            },
            {
                id: 38180,
                cost: 959,
                price: 1598,
                title: "Military Green / M",
                grams: 120,
                color_id: 364,
                size_id: 15,
            },
            {
                id: 38167,
                cost: 959,
                price: 1598,
                title: "Charcoal / M",
                grams: 120,
                color_id: 424,
                size_id: 15,
            },
            {
                id: 38169,
                cost: 959,
                price: 1598,
                title: "Dark Chocolate / M",
                grams: 120,
                color_id: 362,
                size_id: 15,
            },
            {
                id: 38170,
                cost: 959,
                price: 1598,
                title: "Irish Green / M",
                grams: 120,
                color_id: 369,
                size_id: 15,
            },
            {
                id: 38171,
                cost: 959,
                price: 1598,
                title: "Light Blue / M",
                grams: 120,
                color_id: 392,
                size_id: 15,
            },
            {
                id: 38172,
                cost: 959,
                price: 1598,
                title: "Navy / M",
                grams: 120,
                color_id: 511,
                size_id: 15,
            },
            {
                id: 38174,
                cost: 959,
                price: 1598,
                title: "Red / M",
                grams: 120,
                color_id: 423,
                size_id: 15,
            },
            {
                id: 38175,
                cost: 959,
                price: 1598,
                title: "Royal / M",
                grams: 120,
                color_id: 425,
                size_id: 15,
            },
            {
                id: 38177,
                cost: 959,
                price: 1598,
                title: "White / M",
                grams: 120,
                color_id: 521,
                size_id: 15,
            },
            {
                id: 38176,
                cost: 959,
                price: 1598,
                title: "Sport Grey / M",
                grams: 120,
                color_id: 358,
                size_id: 15,
            },
            {
                id: 38192,
                cost: 959,
                price: 1598,
                title: "Black / L",
                grams: 140,
                color_id: 418,
                size_id: 16,
            },
            {
                id: 38194,
                cost: 959,
                price: 1598,
                title: "Military Green / L",
                grams: 140,
                color_id: 364,
                size_id: 16,
            },
            {
                id: 38181,
                cost: 959,
                price: 1598,
                title: "Charcoal / L",
                grams: 140,
                color_id: 424,
                size_id: 16,
            },
            {
                id: 38183,
                cost: 959,
                price: 1598,
                title: "Dark Chocolate / L",
                grams: 140,
                color_id: 362,
                size_id: 16,
            },
            {
                id: 38184,
                cost: 959,
                price: 1598,
                title: "Irish Green / L",
                grams: 140,
                color_id: 369,
                size_id: 16,
            },
            {
                id: 38185,
                cost: 959,
                price: 1598,
                title: "Light Blue / L",
                grams: 140,
                color_id: 392,
                size_id: 16,
            },
            {
                id: 38186,
                cost: 959,
                price: 1598,
                title: "Navy / L",
                grams: 140,
                color_id: 511,
                size_id: 16,
            },
            {
                id: 38188,
                cost: 959,
                price: 1598,
                title: "Red / L",
                grams: 140,
                color_id: 423,
                size_id: 16,
            },
            {
                id: 38189,
                cost: 959,
                price: 1598,
                title: "Royal / L",
                grams: 140,
                color_id: 425,
                size_id: 16,
            },
            {
                id: 38191,
                cost: 959,
                price: 1598,
                title: "White / L",
                grams: 140,
                color_id: 521,
                size_id: 16,
            },
            {
                id: 38190,
                cost: 959,
                price: 1598,
                title: "Sport Grey / L",
                grams: 140,
                color_id: 358,
                size_id: 16,
            },
            {
                id: 38206,
                cost: 959,
                price: 1598,
                title: "Black / XL",
                grams: 160,
                color_id: 418,
                size_id: 17,
            },
            {
                id: 38208,
                cost: 959,
                price: 1598,
                title: "Military Green / XL",
                grams: 160,
                color_id: 364,
                size_id: 17,
            },
            {
                id: 38195,
                cost: 959,
                price: 1598,
                title: "Charcoal / XL",
                grams: 160,
                color_id: 424,
                size_id: 17,
            },
            {
                id: 38197,
                cost: 959,
                price: 1598,
                title: "Dark Chocolate / XL",
                grams: 160,
                color_id: 362,
                size_id: 17,
            },
            {
                id: 38198,
                cost: 959,
                price: 1598,
                title: "Irish Green / XL",
                grams: 160,
                color_id: 369,
                size_id: 17,
            },
            {
                id: 38199,
                cost: 959,
                price: 1598,
                title: "Light Blue / XL",
                grams: 160,
                color_id: 392,
                size_id: 17,
            },
            {
                id: 38200,
                cost: 959,
                price: 1598,
                title: "Navy / XL",
                grams: 160,
                color_id: 511,
                size_id: 17,
            },
            {
                id: 38202,
                cost: 959,
                price: 1598,
                title: "Red / XL",
                grams: 160,
                color_id: 423,
                size_id: 17,
            },
            {
                id: 38203,
                cost: 959,
                price: 1598,
                title: "Royal / XL",
                grams: 160,
                color_id: 425,
                size_id: 17,
            },
            {
                id: 38205,
                cost: 959,
                price: 1598,
                title: "White / XL",
                grams: 160,
                color_id: 521,
                size_id: 17,
            },
            {
                id: 38204,
                cost: 959,
                price: 1598,
                title: "Sport Grey / XL",
                grams: 160,
                color_id: 358,
                size_id: 17,
            },
            {
                id: 38220,
                cost: 1096,
                price: 1827,
                title: "Black / 2XL",
                grams: 180,
                color_id: 418,
                size_id: 18,
            },
            {
                id: 38222,
                cost: 1096,
                price: 1827,
                title: "Military Green / 2XL",
                grams: 180,
                color_id: 364,
                size_id: 18,
            },
            {
                id: 38209,
                cost: 1096,
                price: 1827,
                title: "Charcoal / 2XL",
                grams: 180,
                color_id: 424,
                size_id: 18,
            },
            {
                id: 38211,
                cost: 1096,
                price: 1827,
                title: "Dark Chocolate / 2XL",
                grams: 180,
                color_id: 362,
                size_id: 18,
            },
            {
                id: 38212,
                cost: 1096,
                price: 1827,
                title: "Irish Green / 2XL",
                grams: 180,
                color_id: 369,
                size_id: 18,
            },
            {
                id: 38213,
                cost: 1096,
                price: 1827,
                title: "Light Blue / 2XL",
                grams: 180,
                color_id: 392,
                size_id: 18,
            },
            {
                id: 38214,
                cost: 1096,
                price: 1827,
                title: "Navy / 2XL",
                grams: 180,
                color_id: 511,
                size_id: 18,
            },
            {
                id: 38216,
                cost: 1096,
                price: 1827,
                title: "Red / 2XL",
                grams: 180,
                color_id: 423,
                size_id: 18,
            },
            {
                id: 38217,
                cost: 1096,
                price: 1827,
                title: "Royal / 2XL",
                grams: 180,
                color_id: 425,
                size_id: 18,
            },
            {
                id: 38219,
                cost: 1096,
                price: 1827,
                title: "White / 2XL",
                grams: 180,
                color_id: 521,
                size_id: 18,
            },
            {
                id: 38218,
                cost: 1096,
                price: 1827,
                title: "Sport Grey / 2XL",
                grams: 180,
                color_id: 358,
                size_id: 18,
            },
        ],
    },
    {
        id: 'hoodie',
        title: 'Hoodie',
        color: '#026539',
        providers: [29, 26, 72],
        colors: [521, 418, 358, 395, 364, 369, 367, 392, 425, 511, 423],
        sizes: [14, 15, 16, 17, 18],
        variants: [
            {
                id: 42211,
                cost: 2187,
                price: 3645,
                title: "Charcoal / S",
                grams: 482,
                color_id: 424,
                size_id: 14,
            },
            {
                id: 42212,
                cost: 2187,
                price: 3645,
                title: "Charcoal / M",
                grams: 485,
                color_id: 424,
                size_id: 15,
            },
            {
                id: 42213,
                cost: 2187,
                price: 3645,
                title: "Charcoal / L",
                grams: 541,
                color_id: 424,
                size_id: 16,
            },
            {
                id: 42214,
                cost: 2187,
                price: 3645,
                title: "Charcoal / XL",
                grams: 587,
                color_id: 424,
                size_id: 17,
            },
            {
                id: 42215,
                cost: 2396,
                price: 3993,
                title: "Charcoal / 2XL",
                grams: 644,
                color_id: 424,
                size_id: 18,
            },
            {
                id: 66363,
                cost: 2187,
                price: 3645,
                title: "Heather Navy / S",
                grams: 482,
                color_id: 550,
                size_id: 14,
            },
            {
                id: 66364,
                cost: 2187,
                price: 3645,
                title: "Heather Navy / M",
                grams: 485,
                color_id: 550,
                size_id: 15,
            },
            {
                id: 66365,
                cost: 2187,
                price: 3645,
                title: "Heather Navy / L",
                grams: 541,
                color_id: 550,
                size_id: 16,
            },
            {
                id: 66366,
                cost: 2187,
                price: 3645,
                title: "Heather Navy / XL",
                grams: 587,
                color_id: 550,
                size_id: 17,
            },
            {
                id: 66367,
                cost: 2396,
                price: 3993,
                title: "Heather Navy / 2XL",
                grams: 644,
                color_id: 550,
                size_id: 18,
            },
            {
                id: 42235,
                cost: 2187,
                price: 3645,
                title: "Light Blue / S",
                grams: 482,
                color_id: 392,
                size_id: 14,
            },
            {
                id: 42236,
                cost: 2187,
                price: 3645,
                title: "Light Blue / M",
                grams: 485,
                color_id: 392,
                size_id: 15,
            },
            {
                id: 42237,
                cost: 2187,
                price: 3645,
                title: "Light Blue / L",
                grams: 541,
                color_id: 392,
                size_id: 16,
            },
            {
                id: 42238,
                cost: 2187,
                price: 3645,
                title: "Light Blue / XL",
                grams: 587,
                color_id: 392,
                size_id: 17,
            },
            {
                id: 42239,
                cost: 2396,
                price: 3993,
                title: "Light Blue / 2XL",
                grams: 644,
                color_id: 392,
                size_id: 18,
            },
            {
                id: 32918,
                cost: 2187,
                price: 3645,
                title: "Black / S",
                grams: 482,
                color_id: 418,
                size_id: 14,
            },
            {
                id: 33425,
                cost: 2187,
                price: 3645,
                title: "Military Green / S",
                grams: 482,
                color_id: 364,
                size_id: 14,
            },
            {
                id: 32878,
                cost: 2187,
                price: 3645,
                title: "Dark Heather / S",
                grams: 482,
                color_id: 367,
                size_id: 14,
            },
            {
                id: 33369,
                cost: 2187,
                price: 3645,
                title: "Irish Green / S",
                grams: 482,
                color_id: 369,
                size_id: 14,
            },
            {
                id: 32886,
                cost: 2187,
                price: 3645,
                title: "Maroon / S",
                grams: 482,
                color_id: 395,
                size_id: 14,
            },
            {
                id: 32894,
                cost: 2187,
                price: 3645,
                title: "Navy / S",
                grams: 482,
                color_id: 511,
                size_id: 14,
            },
            {
                id: 33385,
                cost: 2187,
                price: 3645,
                title: "Red / S",
                grams: 482,
                color_id: 423,
                size_id: 14,
            },
            {
                id: 33393,
                cost: 2187,
                price: 3645,
                title: "Royal / S",
                grams: 482,
                color_id: 425,
                size_id: 14,
            },
            {
                id: 32910,
                cost: 2187,
                price: 3645,
                title: "White / S",
                grams: 482,
                color_id: 521,
                size_id: 14,
            },
            {
                id: 32902,
                cost: 2187,
                price: 3645,
                title: "Sport Grey / S",
                grams: 482,
                color_id: 358,
                size_id: 14,
            },
            {
                id: 32919,
                cost: 2187,
                price: 3645,
                title: "Black / M",
                grams: 485,
                color_id: 418,
                size_id: 15,
            },
            {
                id: 33426,
                cost: 2187,
                price: 3645,
                title: "Military Green / M",
                grams: 485,
                color_id: 364,
                size_id: 15,
            },
            {
                id: 32879,
                cost: 2187,
                price: 3645,
                title: "Dark Heather / M",
                grams: 485,
                color_id: 367,
                size_id: 15,
            },
            {
                id: 33370,
                cost: 2187,
                price: 3645,
                title: "Irish Green / M",
                grams: 485,
                color_id: 369,
                size_id: 15,
            },
            {
                id: 32887,
                cost: 2187,
                price: 3645,
                title: "Maroon / M",
                grams: 485,
                color_id: 395,
                size_id: 15,
            },
            {
                id: 32895,
                cost: 2187,
                price: 3645,
                title: "Navy / M",
                grams: 485,
                color_id: 511,
                size_id: 15,
            },
            {
                id: 33386,
                cost: 2187,
                price: 3645,
                title: "Red / M",
                grams: 485,
                color_id: 423,
                size_id: 15,
            },
            {
                id: 33394,
                cost: 2187,
                price: 3645,
                title: "Royal / M",
                grams: 485,
                color_id: 425,
                size_id: 15,
            },
            {
                id: 32911,
                cost: 2187,
                price: 3645,
                title: "White / M",
                grams: 485,
                color_id: 521,
                size_id: 15,
            },
            {
                id: 32903,
                cost: 2187,
                price: 3645,
                title: "Sport Grey / M",
                grams: 485,
                color_id: 358,
                size_id: 15,
            },
            {
                id: 32920,
                cost: 2187,
                price: 3645,
                title: "Black / L",
                grams: 541,
                color_id: 418,
                size_id: 16,
            },
            {
                id: 33427,
                cost: 2187,
                price: 3645,
                title: "Military Green / L",
                grams: 541,
                color_id: 364,
                size_id: 16,
            },
            {
                id: 32880,
                cost: 2187,
                price: 3645,
                title: "Dark Heather / L",
                grams: 541,
                color_id: 367,
                size_id: 16,
            },
            {
                id: 33371,
                cost: 2187,
                price: 3645,
                title: "Irish Green / L",
                grams: 541,
                color_id: 369,
                size_id: 16,
            },
            {
                id: 32888,
                cost: 2187,
                price: 3645,
                title: "Maroon / L",
                grams: 541,
                color_id: 395,
                size_id: 16,
            },
            {
                id: 32896,
                cost: 2187,
                price: 3645,
                title: "Navy / L",
                grams: 541,
                color_id: 511,
                size_id: 16,
            },
            {
                id: 33387,
                cost: 2187,
                price: 3645,
                title: "Red / L",
                grams: 541,
                color_id: 423,
                size_id: 16,
            },
            {
                id: 33395,
                cost: 2187,
                price: 3645,
                title: "Royal / L",
                grams: 541,
                color_id: 425,
                size_id: 16,
            },
            {
                id: 32912,
                cost: 2187,
                price: 3645,
                title: "White / L",
                grams: 541,
                color_id: 521,
                size_id: 16,
            },
            {
                id: 32904,
                cost: 2187,
                price: 3645,
                title: "Sport Grey / L",
                grams: 541,
                color_id: 358,
                size_id: 16,
            },
            {
                id: 32921,
                cost: 2187,
                price: 3645,
                title: "Black / XL",
                grams: 587,
                color_id: 418,
                size_id: 17,
            },
            {
                id: 33428,
                cost: 2187,
                price: 3645,
                title: "Military Green / XL",
                grams: 587,
                color_id: 364,
                size_id: 17,
            },
            {
                id: 32881,
                cost: 2187,
                price: 3645,
                title: "Dark Heather / XL",
                grams: 587,
                color_id: 367,
                size_id: 17,
            },
            {
                id: 33372,
                cost: 2187,
                price: 3645,
                title: "Irish Green / XL",
                grams: 587,
                color_id: 369,
                size_id: 17,
            },
            {
                id: 32889,
                cost: 2187,
                price: 3645,
                title: "Maroon / XL",
                grams: 587,
                color_id: 395,
                size_id: 17,
            },
            {
                id: 32897,
                cost: 2187,
                price: 3645,
                title: "Navy / XL",
                grams: 587,
                color_id: 511,
                size_id: 17,
            },
            {
                id: 33388,
                cost: 2187,
                price: 3645,
                title: "Red / XL",
                grams: 587,
                color_id: 423,
                size_id: 17,
            },
            {
                id: 33396,
                cost: 2187,
                price: 3645,
                title: "Royal / XL",
                grams: 587,
                color_id: 425,
                size_id: 17,
            },
            {
                id: 32913,
                cost: 2187,
                price: 3645,
                title: "White / XL",
                grams: 587,
                color_id: 521,
                size_id: 17,
            },
            {
                id: 32905,
                cost: 2187,
                price: 3645,
                title: "Sport Grey / XL",
                grams: 587,
                color_id: 358,
                size_id: 17,
            },
            {
                id: 32922,
                cost: 2396,
                price: 3993,
                title: "Black / 2XL",
                grams: 644,
                color_id: 418,
                size_id: 18,
            },
            {
                id: 33429,
                cost: 2396,
                price: 3993,
                title: "Military Green / 2XL",
                grams: 644,
                color_id: 364,
                size_id: 18,
            },
            {
                id: 32882,
                cost: 2396,
                price: 3993,
                title: "Dark Heather / 2XL",
                grams: 644,
                color_id: 367,
                size_id: 18,
            },
            {
                id: 33373,
                cost: 2396,
                price: 3993,
                title: "Irish Green / 2XL",
                grams: 644,
                color_id: 369,
                size_id: 18,
            },
            {
                id: 32890,
                cost: 2396,
                price: 3993,
                title: "Maroon / 2XL",
                grams: 644,
                color_id: 395,
                size_id: 18,
            },
            {
                id: 32898,
                cost: 2396,
                price: 3993,
                title: "Navy / 2XL",
                grams: 644,
                color_id: 511,
                size_id: 18,
            },
            {
                id: 33389,
                cost: 2396,
                price: 3993,
                title: "Red / 2XL",
                grams: 644,
                color_id: 423,
                size_id: 18,
            },
            {
                id: 33397,
                cost: 2396,
                price: 3993,
                title: "Royal / 2XL",
                grams: 644,
                color_id: 425,
                size_id: 18,
            },
            {
                id: 32914,
                cost: 2396,
                price: 3993,
                title: "White / 2XL",
                grams: 644,
                color_id: 521,
                size_id: 18,
            },
            {
                id: 32906,
                cost: 2396,
                price: 3993,
                title: "Sport Grey / 2XL",
                grams: 644,
                color_id: 358,
                size_id: 18,
            },
        ],
    },
    {
        id: 'raglan-tee',
        title: 'Raglan Tee',
        color: '#e0824b',
        providers: [27, 6],
        colors: [1535, 1062, 1792, 1536, 1058, 1795, 1750],
        sizes: [14, 15, 16, 17, 18],
        variants: [
            {
                id: 33522,
                cost: 1782,
                price: 2970,
                title: "Royal/White / S",
                grams: 110,
                color_id: 1058,
                size_id: 14,
            },
            {
                id: 36255,
                cost: 1782,
                price: 2970,
                title: "Asphalt/White / S",
                grams: 110,
                color_id: 1535,
                size_id: 14,
            },
            {
                id: 36256,
                cost: 1782,
                price: 2970,
                title: "Red/White / S",
                grams: 110,
                color_id: 1536,
                size_id: 14,
            },
            {
                id: 33523,
                cost: 1782,
                price: 2970,
                title: "Royal/White / M",
                grams: 131,
                color_id: 1058,
                size_id: 15,
            },
            {
                id: 36257,
                cost: 1782,
                price: 2970,
                title: "Asphalt/White / M",
                grams: 131,
                color_id: 1535,
                size_id: 15,
            },
            {
                id: 36258,
                cost: 1782,
                price: 2970,
                title: "Red/White / M",
                grams: 131,
                color_id: 1536,
                size_id: 15,
            },
            {
                id: 33524,
                cost: 1782,
                price: 2970,
                title: "Royal/White / L",
                grams: 158,
                color_id: 1058,
                size_id: 16,
            },
            {
                id: 36259,
                cost: 1782,
                price: 2970,
                title: "Asphalt/White / L",
                grams: 158,
                color_id: 1535,
                size_id: 16,
            },
            {
                id: 36260,
                cost: 1782,
                price: 2970,
                title: "Red/White / L",
                grams: 158,
                color_id: 1536,
                size_id: 16,
            },
            {
                id: 33525,
                cost: 1782,
                price: 2970,
                title: "Royal/White / XL",
                grams: 190,
                color_id: 1058,
                size_id: 17,
            },
            {
                id: 36261,
                cost: 1782,
                price: 2970,
                title: "Asphalt/White / XL",
                grams: 190,
                color_id: 1535,
                size_id: 17,
            },
            {
                id: 36262,
                cost: 1782,
                price: 2970,
                title: "Red/White / XL",
                grams: 190,
                color_id: 1536,
                size_id: 17,
            },
            {
                id: 33526,
                cost: 1993,
                price: 3322,
                title: "Royal/White / 2XL",
                grams: 228,
                color_id: 1058,
                size_id: 18,
            },
            {
                id: 36263,
                cost: 1993,
                price: 3322,
                title: "Asphalt/White / 2XL",
                grams: 228,
                color_id: 1535,
                size_id: 18,
            },
            {
                id: 36264,
                cost: 1993,
                price: 3322,
                title: "Red/White / 2XL",
                grams: 228,
                color_id: 1536,
                size_id: 18,
            },
            {
                id: 39151,
                cost: 1782,
                price: 2970,
                title: "White/Black / S",
                grams: 110,
                color_id: 1750,
                size_id: 14,
            },
            {
                id: 39193,
                cost: 1782,
                price: 2970,
                title: "Green/White / S",
                grams: 110,
                color_id: 1792,
                size_id: 14,
            },
            {
                id: 39196,
                cost: 1782,
                price: 2970,
                title: "Navy/White / S",
                grams: 110,
                color_id: 1795,
                size_id: 14,
            },
            {
                id: 39217,
                cost: 1782,
                price: 2970,
                title: "Black/White / S",
                grams: 110,
                color_id: 1062,
                size_id: 14,
            },
            {
                id: 39229,
                cost: 1782,
                price: 2970,
                title: "White/Black / M",
                grams: 131,
                color_id: 1750,
                size_id: 15,
            },
            {
                id: 39271,
                cost: 1782,
                price: 2970,
                title: "Green/White / M",
                grams: 131,
                color_id: 1792,
                size_id: 15,
            },
            {
                id: 39274,
                cost: 1782,
                price: 2970,
                title: "Navy/White / M",
                grams: 131,
                color_id: 1795,
                size_id: 15,
            },
            {
                id: 39295,
                cost: 1782,
                price: 2970,
                title: "Black/White / M",
                grams: 131,
                color_id: 1062,
                size_id: 15,
            },
            {
                id: 39307,
                cost: 1782,
                price: 2970,
                title: "White/Black / L",
                grams: 158,
                color_id: 1750,
                size_id: 16,
            },
            {
                id: 39349,
                cost: 1782,
                price: 2970,
                title: "Green/White / L",
                grams: 158,
                color_id: 1792,
                size_id: 16,
            },
            {
                id: 39352,
                cost: 1782,
                price: 2970,
                title: "Navy/White / L",
                grams: 158,
                color_id: 1795,
                size_id: 16,
            },
            {
                id: 39373,
                cost: 1782,
                price: 2970,
                title: "Black/White / L",
                grams: 158,
                color_id: 1062,
                size_id: 16,
            },
            {
                id: 39385,
                cost: 1782,
                price: 2970,
                title: "White/Black / XL",
                grams: 190,
                color_id: 1750,
                size_id: 17,
            },
            {
                id: 39427,
                cost: 1782,
                price: 2970,
                title: "Green/White / XL",
                grams: 190,
                color_id: 1792,
                size_id: 17,
            },
            {
                id: 39430,
                cost: 1782,
                price: 2970,
                title: "Navy/White / XL",
                grams: 190,
                color_id: 1795,
                size_id: 17,
            },
            {
                id: 39451,
                cost: 1782,
                price: 2970,
                title: "Black/White / XL",
                grams: 190,
                color_id: 1062,
                size_id: 17,
            },
            {
                id: 39463,
                cost: 1993,
                price: 3322,
                title: "White/Black / 2XL",
                grams: 228,
                color_id: 1750,
                size_id: 18,
            },
            {
                id: 39505,
                cost: 1993,
                price: 3322,
                title: "Green/White / 2XL",
                grams: 228,
                color_id: 1792,
                size_id: 18,
            },
            {
                id: 39508,
                cost: 1993,
                price: 3322,
                title: "Navy/White / 2XL",
                grams: 228,
                color_id: 1795,
                size_id: 18,
            },
            {
                id: 39529,
                cost: 1993,
                price: 3322,
                title: "Black/White / 2XL",
                grams: 228,
                color_id: 1062,
                size_id: 18,
            }
        ],
    },
    {
        id: 'socks',
        title: 'Socks',
        providers: [],
    },
    {
        id: 'pillows',
        title: 'Pillows',
        providers: [],
    },
]

export const EU_COUNTRIES = ['DE', 'BV', 'GE', 'SM', 'GI', 'GG', 'AT', 'HU', 'MD', 'HR', 'BE', 'IM', 'GR', 'IT', 'BY', 'GL', 'GP', 'LU', 'VA', 'JE', 'SK', 'BG', 'MK', 'PT', 'RE', 'FR', 'RO', 'TR', 'SI', 'XK', 'CZ', 'RS', 'ES', 'MC', 'ME', 'UA', 'AL', 'AM', 'CY', 'AX', 'AD', 'FO', 'BA', 'NL', 'MT']

export function getShippingOptions(country) {
    switch (EU_COUNTRIES.includes(country) ? 'EU' : country) {
        case 'US':
            return {
                't-shirt': {
                    provider_id: 29,
                    first_item: 475,
                    add_item: 240,
                    currency: 'usd'
                },
                'hoodie': {
                    provider_id: 29,
                    first_item: 849,
                    add_item: 209,
                    currency: 'usd'
                },
                'mugs-white': {
                    provider_id: 29,
                    first_item: 849,
                    add_item: 209,
                    currency: 'usd'
                },
                'mugs-color': {
                    provider_id: 29,
                    first_item: 849,
                    add_item: 209,
                    currency: 'usd'
                },
                'raglan-tee': {
                    provider_id: 27,
                    first_item: 849,
                    add_item: 330,
                    currency: 'usd'
                },
            }
        case 'CA':
            return {
                't-shirt': {
                    provider_id: 29,
                    first_item: 939,
                    add_item: 439,
                    currency: 'usd'
                },
                'hoodie': {
                    provider_id: 29,
                    first_item: 1269,
                    add_item: 659,
                    currency: 'usd'
                },
                'raglan-tee': {
                    provider_id: 27,
                    first_item: 679,
                    add_item: 219,
                    currency: 'usd'
                },
            }
        case 'PL':
            return {
                't-shirt': {
                    provider_id: 87,
                    first_item: 499,
                    add_item: 119,
                    currency: 'usd'
                },
                'hoodie': {
                    provider_id: 26,
                    first_item: 699,
                    add_item: 239,
                    currency: 'usd'
                },
                'raglan-tee': {
                    provider_id: 6,
                    first_item: 749,
                    add_item: 129,
                    currency: 'usd'
                },
            }
        case 'EU':
            return {
                't-shirt': {
                    provider_id: 87,
                    first_item: 569,
                    add_item: 199,
                    currency: 'usd'
                },
                'hoodie': {
                    provider_id: 26,
                    first_item: 699,
                    add_item: 239,
                    currency: 'usd'
                },
                'raglan-tee': {
                    provider_id: 6,
                    first_item: 749,
                    add_item: 129,
                    currency: 'usd'
                },
            }
        case 'UK':
            return {
                't-shirt': {
                    provider_id: 72,
                    first_item: 429,
                    add_item: 199,
                    currency: 'usd'
                },
                'hoodie': {
                    provider_id: 72,
                    first_item: 759,
                    add_item: 299,
                    currency: 'usd'
                },
                'raglan-tee': {
                    provider_id: 6,
                    first_item: 398,
                    add_item: 129,
                    currency: 'usd'
                },
            }
        case 'AU':
            return {
                't-shirt': {
                    provider_id: 29,
                    first_item: 1249,
                    add_item: 499,
                    currency: 'usd'
                },
                'hoodie': {
                    provider_id: 29,
                    first_item: 2199,
                    add_item: 999,
                    currency: 'usd'
                },
                'raglan-tee': {
                    provider_id: 27,
                    first_item: 1099,
                    add_item: 549,
                    currency: 'usd'
                },
            }
        default: return {
            't-shirt': {
                provider_id: 29,
                first_item: 1000,
                add_item: 400,
                currency: 'usd'
            },
            'hoodie': {
                provider_id: 29,
                first_item: 1500,
                add_item: 1000,
                currency: 'usd'
            },
            'raglan-tee': {
                provider_id: 27,
                first_item: 1099,
                add_item: 549,
                currency: 'usd'
            },
        }
    }
}

export function convertDolarToCurrency(value, currency) {
    if (currency === 'usd')
        return value
    if (currency === 'gbp')
        return Math.round(value * 0.82)
    if (currency === 'eur')
        return Math.round(value * 0.94)
    if (currency === 'brl')
        return Math.round(value * 4.87)
    console.error('Currency not found')
    return null
}

export function getCurrencyByCode(code) {
    if (code === 'brl')
        return { code: 'brl', symbol: 'R$' }
    if (code === 'gbp')
        return { code: 'gbp', symbol: '£' }
    if (code === 'eur')
        return { code: 'eur', symbol: '€' }
    if (code === 'usd')
        return { code: 'usd', symbol: '$' }
    console.error('Currency not found')
    return null
}